export const SET_GET_LIST_ORGANIZATION = "SET_GET_LIST_ORGANIZATION";
export const SET_ACTIVATE_ORGANIZATION = "SET_ACTIVATE_ORGANIZATION";
export const SET_REJECT_ORGANIZATION = "SET_REJECT_ORGANIZATION";
