export const SET_APPROVE_EVENT = "SET_APPROVE_EVENT";
export const SET_REJECT_EVENT = "SET_REJECT_EVENT";
export const SET_LIST_EVENTS_ALL = "SET_LIST_EVENTS_ALL";
export const SET_LIST_EVENTS_HOT = "SET_LIST_EVENTS_HOT";
export const SET_LIST_DETAIL_EVENTS = "SET_LIST_DETAIL_EVENTS";
