export const SET_GET_LIST_EVENTS = "SET_GET_LIST_EVENTS";
export const SET_GET_LIST_EVENTS_HOT = "SET_GET_LIST_EVENTS_HOT";
export const SET_GET_LIST_DETAIL_EVENTS = "SET_GET_LIST_DETAIL_EVENTS";
export const SET_GET_LIST_CITY = "SET_GET_LIST_CITY";
export const SET_CARD_LIST = "SET_CARD_LIST";
