export const SET_GET_LIST_ALL_USERS = "GET_LIST_ALL_USERS";
export const SET_GET_LIST_USERS_DETAIL = "GET_LIST_USERS_DETAIL";
export const SET_BLOCK_USER = "BLOCK_USER";
export const SET_UNLOCK_USER = "UNLOCK_USER";
