export const SET_GET_MY_LIST_ORDER = "SET_GET_MY_LIST_ORDER";
export const SET_GET_MY_LIST_ORDER_STATUS = "SET_GET_MY_LIST_ORDER_STATUS";
export const SET_GET_MY_LIST_ORDER_DETAIL = "SET_GET_MY_LIST_ORDER_DETAIL";
