export const SET_USER_LOGIN = "SET_USER_LOGIN";
export const SET_USER_REGISTER = "SET_USER_REGISTER";
export const SET_USER_VERIFY = "SET_USER_VERIFY";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_USER_LIST = "SET_USER_LIST";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_USER_LOGOUT = "SET_USER_LOGOUT";
export const SET_USER_ACCESS_AUTHORIZATION = "SET_USER_ACCESS_AUTHORIZATION";
